language: ruby
cache: bundler
rvm:
  - 2.0.0
env:
  - DB=postgres
before_install:
  - gem install bundler --pre
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database chirch_app_test;' -U postgres
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"  # Capybara webkit needs it.
  - sleep 3                                                                     # give Web server some time to bind to sockets, etc
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec
  - bundle exec cucumber

