language: ruby
bundler_args: --without development --deployment
cache: bundler
branches:
  only:
    - master
rvm:
  - 2.0.0
env:
  - DB=postgres
before_install:
  - gem install bundler --pre                                                   # pre release version allow to install gems parallel.
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database chirch_app_test;' -U postgres
  - "export DISPLAY=:99.0"                                                      # cucumber needs that
  - "sh -e /etc/init.d/xvfb start"                                              # and that to run js specs heedlessly.
  - sleep 3                                                                     # give xvfb some time to start
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - bundle exec rake db:test:prepare
  - bundle exec rspec
  - bundle exec cucumber -f progress

