development:
  adapter: postgresql
  database: chirch_app_development
  username: postgres
  password:
  host: localhost
  encoding: UTF8

test:
  adapter: postgresql
  database: chirch_app_test
  username: postgres
  password:
  host: localhost
  encoding: UTF8

production:
  adapter: postgresql
  database: chirch_app_production
  username: postgres
  password:
  host: localhost
  encoding: UTF8