development:
  adapter: postgresql
  database: chirch_app_development
  username: postgres
  password: def!ne_p0stgre
  host: localhost
  encoding: UTF8

test:
  adapter: postgresql
  database: chirch_app_test
  username: postgres
  password: def!ne_p0stgre
  host: localhost
  encoding: UTF8
